# NumPy
- Numeric + Python = Numpy
- 수학 및 과학 연산을 위한 파이썬 패키지
- 배열이나 행렬 계산에 용이한 메서드 제공
- 반복문 없이 데이터 배열에 대한 처리 지원
- 선형대수와 관련된 다양한 기능 제공
- 관련 사이트
    - http://www.numpy.org
    - http://cs231n.github.io/python-numpy-tutorial/#numpy
    - https://datascienceschool.net

In [2]:
import numpy as np

np.__version__

'1.25.0'

In [10]:
# 넘파이 배열 생성
'''
Numpy np.array(리스트|튜플|집합)
    - 리스트변수 생성 후 np.array(리스트명)
    - np.array([값1, 값2....])
    - 리스트 형태는 실수, 정수, 문자 넘파이 배열 가능
'''

myList = [1,2,3,4,5]
print(myList)
print(type(myList))
print()

arr = np.array(myList)
print(arr)
print(type(arr))
arr

[1, 2, 3, 4, 5]
<class 'list'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [17]:
# 정수 + 실수 리스트 => 넘파이 배열
print(np.array([1,2,3.5,6,10]))

# 문자열 리스트 => 넘파이 배열
myList = ['강아지','원숭이','꽃','45,100']
print(np.array(myList), type(np.array(myList)))

[ 1.   2.   3.5  6.  10. ]
['강아지' '원숭이' '꽃' '45,100'] <class 'numpy.ndarray'>


In [21]:
# 리스트는 데이터형이 혼합되어도 되지만 넘파이 배열은 데이터형이 하나여야 한다!!

myList1 = [1,2,3.14,5]
myList2 = [1, 3.14, 'cat', 'zero']
print(myList1, myList2) # 리스트는 데이터형 변환 없음

arr1 = np.array(myList1)
arr2 = np.array(myList2)

print(arr1, arr2) # 넘파이 배열은 하나의 데이터형으로 변환

[1, 2, 3.14, 5] [1, 3.14, 'cat', 'zero']
[1.   2.   3.14 5.  ] ['1' '3.14' 'cat' 'zero']


### 넘파이 구조 : shape
- 넘파이배열명.shape
    - 1차원 넘파이 배열의 구조(형태) = (갯수,) = tuple 구조
    - 2차원 넘파이 배열의 구조(형태) = (행수,열수) = tuple 구조
    - ndim; number of dimension : 차원, 정수 형태로 반환
    - 넘파이 배열 안의 배열은 데이터 길이가 같아야 한다!
    - len(): 1차원은 전체 갯수, 2차원은 행수, type(): 넘파이 배열
    - size: 전체 데이터 갯수

In [38]:
# 1차원 리스트 => 넘파이 배열
arr1 = np.array(['트와이스','워너원','위너','방탄소년단','레드벨벳'])
print(arr1.shape) # (갯수,)를 튜플 형태로 반환
print(arr)
# arr

(5,)
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [39]:
# 2차원 리스트 => 넘파이 배열
colourList = [['red','green','blue'], ['빨강','초록','파랑'], ['white', 'black', 'gray']]

colourNp = np.array(colourList)
print(type(colourNp))
print(len(colourNp), colourNp.shape) # (행수, 열수) 튜플 형태로 반환
print(colourNp)
# colourNp
print(colourNp.shape[0], colourNp.shape[1])

<class 'numpy.ndarray'>
3 (3, 3)
[['red' 'green' 'blue']
 ['빨강' '초록' '파랑']
 ['white' 'black' 'gray']]
3 3


### 초기값이 지정된 넘파이 배열
- np.zeros(갯수) : 0으로 구성된 1차원 넘파이 배열
- np.zeros([행수,열수]) : 0으로 구성된 2차원 넘파이 배열
- np.ones(갯수) : 1로 구성된 1차원 넘파이 배열
- np.ones([행수,열수]) : 1로 구성된 2차원 넘파이 배열
- np.full(갯수, 초기값) : 지정한 값으로 지정하는 1차원 넘파이 배열
- np.full([행수,열수], 초기값) : 지정한 값으로 지정하는 2차원 넘파이 배열

In [44]:
arr = np.full([3,5], 7)
arr

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

### 초기값이 지정된 넘파이 배열
- np.eye(갯수) : 대각선의 원소가 모두 1이고 나머지 원소는 0인 정사각형 2차원 넘파이 배열 생성
- np.tri(갯수) : 대각선을 기준으로 삼각형 형태로 1이 지정되는 정사각형 2차원 넘파이 배열 생성
- np.?_like(넘파이배열명) : 지정된 넘파이 배열과 shape가 같은 넘파이 배열 생성
    - np.zeros_like(넘파이배열명)
    - np.ones_like(넘파이배열명)
    - np.full_like(넘파이배열명, 값)
    - np.empty_like(넘파이배열명)

In [66]:
print(np.eye(5))
print('='*50)

print(np.tri(5))
print('='*50)

myArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # str 값이 있을 때랑 없을 때 비교해서 보기!! str 형태로 zeros 출력하면 값이 없는 형태로 반환
print(myArr)
print(np.zeros_like(myArr))
print(np.ones_like(myArr))
print(np.full_like(myArr, 3.5))
# print(np.full_like(myArr, True))
print('='*50)

print(np.empty_like(myArr))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


### 초기값이 지정된 넘파이 배열
- 증가되는 숫자값으로 넘파이배열 생성하기
    - np.arange(start,end,step) => 넘파이배열. end-1 까지만 생성
    - np.arange(end) => 넘파이배열. 0~ end-1 까지만 생성
    - np.linspace(start,end,n) => 범위 내에서 n개를 균등 간격으로 생성

In [68]:
# 참고
# range(start,end,step) => 리스트. end-1 까지만 생성
print(range(0,10), type(range(0,10)))
print(list(range(0,10)), type(list(range(0,10))))
print(range(0,10,2))
print(list(range(0,10,2)))

range(0, 10) <class 'range'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>
range(0, 10, 2)
[0, 2, 4, 6, 8]


In [100]:
test = np.arange(1,10,3)
print(test)
print('======================')
print('1',np.arange(10))
print('2',np.arange(1, 10, 2))
print('3',np.arange(10, 21))
print('4',np.linspace(0, 1, 5))
print('5',np.linspace(-10, 10, 5))

[1 4 7]
1 [0 1 2 3 4 5 6 7 8 9]
2 [1 3 5 7 9]
3 [10 11 12 13 14 15 16 17 18 19 20]
4 [0.   0.25 0.5  0.75 1.  ]
5 [-10.  -5.   0.   5.  10.]


### 넘파이 데이타형 : dtype
- 넘파이배열 값의 데이터형을 반환
- dtype : data type
- type(변수/값) => 전체객체의 자료형
- 넘파이배열.dtype : int32, <U2 , float64
- 넘파이배열 생성시 자료형 함께 지정하기
    - np.array(리스트, dtype=자료형)

In [112]:
arr1 = np.array([1,2,3,4,5])
print(arr1.dtype)
print(arr1)
print()

arr1 = np.array([1,2,3,4,5], dtype=float)
print(arr1.dtype)
print(arr1)

int32
[1 2 3 4 5]

float64
[1. 2. 3. 4. 5.]


In [102]:
arr2 = np.array([5.5, 6, 7, 10.0])
arr2.dtype

dtype('float64')

In [104]:
arr3 = np.array([1,2,'3',4,5])
arr3.dtype

dtype('<U11')

In [106]:
arr4 = np.array(['1','2','3'])
arr4.dtype

dtype('<U1')

In [122]:
#  데이타형 : dtype

# 실수형으로 넘파이 배열 생성
arr = np.array([1,2,3,4,5], dtype=float)
print(type(arr), arr.dtype)
print(arr)
print()

# 문자열형으로 넘파이 배열 생성
arr = np.array([1,2,3,4,5], dtype=str)
print(type(arr), arr.dtype)
print(arr)
print()

# 논리형으로 넘파이 배열 생성
arr = np.array([0,1,2,3,4,5,'사과',''], dtype=bool)
print(type(arr), arr.dtype)
print(arr)

<class 'numpy.ndarray'> float64
[1. 2. 3. 4. 5.]

<class 'numpy.ndarray'> <U1
['1' '2' '3' '4' '5']

<class 'numpy.ndarray'> bool
[False  True  True  True  True  True  True False]


In [130]:
# 데이터형 변환(casting)
arr1 = np.array([[0,1,2,3,4],[0,0,0,1,0],[5,7,1,32,-9]])
print(arr1, ' : ', arr1.dtype, '\n')

arr2 = arr1.astype(float)
print(arr2, ' : ', arr2.dtype, '\n')

arr3 = arr1.astype('<U1')
print(arr3, ' : ', arr3.dtype, '\n')

arr4 = arr1.astype(bool)
print(arr4, ' : ', arr4.dtype)

[[ 0  1  2  3  4]
 [ 0  0  0  1  0]
 [ 5  7  1 32 -9]]  :  int32 

[[ 0.  1.  2.  3.  4.]
 [ 0.  0.  0.  1.  0.]
 [ 5.  7.  1. 32. -9.]]  :  float64 

[['0' '1' '2' '3' '4']
 ['0' '0' '0' '1' '0']
 ['5' '7' '1' '3' '-']]  :  <U1 

[[False  True  True  True  True]
 [False False False  True False]
 [ True  True  True  True  True]]  :  bool


### 배열의 구조 변경
- 1차원 => 2차원 / 2차원=>1차원
- 넘파이배열명.reshape(행수,열수) : 1차원=>2차원, 2차원=>2차원
- 넘파이배열명.flatten() : 2차원 => 1차원 | 쫙 펼쳐서 1차원의 배열에 다 담음
- 넘파이배열명.reshape(-1, ?) : 전체요소(size)기준. 2차원 전체 갯수 기반으로 row 개수 선정

In [135]:
# 1차원(5) => 2차원(5행1열)
npArr1 = np.array([100, 300, 500, 1, 2])
print(f'npArr1 \n{npArr1}, \n차원={npArr1.ndim}, 구조={npArr1.shape}')

npArr2 = npArr1.reshape(5,1)
print(f'\n npArr2 \n {npArr2}, \n차원={npArr2.ndim}, 구조={npArr2.shape}')

npArr1 
[100 300 500   1   2], 
차원=1, 구조=(5,)

 npArr2 
 [[100]
 [300]
 [500]
 [  1]
 [  2]], 
차원=2, 구조=(5, 1)


In [136]:
# 2차원(2행5열) => 2차원(5행2열)
npArr3 = np.array([['a','b','c','d','e'],['a','b','c','d','e']])
print(f'npArr3 \n{npArr3}\n차원={npArr3.ndim}, 구조={npArr3.shape}')

npArr4 = npArr3.reshape(5,2)
print(f'\n\n npArr4 \n{npArr4}\n차원={npArr4.ndim}, 구조={npArr4.shape}')

npArr3 
[['a' 'b' 'c' 'd' 'e']
 ['a' 'b' 'c' 'd' 'e']]
차원=2, 구조=(2, 5)


 npArr4 
[['a' 'b']
 ['c' 'd']
 ['e' 'a']
 ['b' 'c']
 ['d' 'e']]
차원=2, 구조=(5, 2)


In [137]:
# 2차원(2행5열) => 1차원(10)
npArr5 = np.array([[1,4,5,6],[56,23,45,67],[8,4,6,10]])
print(f'npArr5\n{npArr5}\n차원={npArr5.ndim}, 구조={npArr5.shape}\n')

npArr6 = npArr5.flatten()
print(f'npArr6\n{npArr6}\n차원={npArr6.ndim}, 구조={npArr6.shape}')

npArr5
[[ 1  4  5  6]
 [56 23 45 67]
 [ 8  4  6 10]]
차원=2, 구조=(3, 4)

npArr6
[ 1  4  5  6 56 23 45 67  8  4  6 10]
차원=1, 구조=(12,)


In [152]:
# reshape(행수, 열수) | reshape(-1, 열수)
# -1, n => "-1 부분은 너가 알아서 하고, n개 요소씩 담아서 배열로 만들어 줘"
npArr8=np.array([30, 80, 100, 79, 80, 100])
print(npArr8)
print(f'차원={npArr8.ndim}, 구조={npArr8.shape}, 총갯수={npArr8.size}\n')

npArr9=npArr8.reshape(-1,2)
print(npArr9)
print(f'차원={npArr9.ndim}, 구조={npArr9.shape}, 총갯수={npArr9.size}\n')

npArr10=npArr8.reshape(-1,3)
print(npArr10)
print(f'차원={npArr10.ndim}, 구조={npArr10.shape}, 총갯수={npArr10.size}\n')

try:
    npArr10=npArr8.reshape(-1,5)
    print(npArr10)
    print(f'차원={npArr10.ndim}, 구조={npArr10.shape}, 총갯수={npArr10.size}\n')
except:
    print('오류 발생!')
    print('reshape(-1,3)으로 강제 반환합니다.')
finally:
    npArr10=npArr8.reshape(-1,3)
    print(npArr10)
    print(f'차원={npArr10.ndim}, 구조={npArr10.shape}, 총갯수={npArr10.size}\n')

[ 30  80 100  79  80 100]
차원=1, 구조=(6,), 총갯수=6

[[ 30  80]
 [100  79]
 [ 80 100]]
차원=2, 구조=(3, 2), 총갯수=6

[[ 30  80 100]
 [ 79  80 100]]
차원=2, 구조=(2, 3), 총갯수=6

오류 발생!
reshape(-1,3)으로 강제 반환합니다.
[[ 30  80 100]
 [ 79  80 100]]
차원=2, 구조=(2, 3), 총갯수=6



### 배열의 축 변경
- 넘파이배열명.T
- T는 Transpose. 행과 열이 서로 변경된다.
- 넘파이배열명.swapaxes(0, 1), 넘파이배열명.swapaxes(1, 0)

In [170]:
arr1 = np.arange(1,13).reshape(4,3)
print(arr1)
print()
# 행, 열 변경
print('arr1의 행과 열이 서로 변경!')
print(arr1.T)
print('===================')

arr2 = arr1.swapaxes(0,1)
print(arr2)
print()

arr3 = arr2.swapaxes(1,0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

arr1의 행과 열이 서로 변경!
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 행열 연산

In [186]:
# 넘파이 배열 연산
# 같은 인덱스 위치끼리 연산 가능

list1 = [1,2,3,4,5]
list2 = [10,20,30,40,50]
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(list1+list2)
print(arr1+arr2)

print(list1*3)
print(arr1*3)

# print(list1//3) # error!
print(arr1//3)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]
[0 0 1 1 1]


In [184]:
# arange로 범위 단위 연산 가능
arr1 = np.arange(20,26)
arr2 = np.arange(10,16)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 // arr2) # 정수 몫
# print(arr1 / arr2)
print(arr1*5)
print(arr1**2)

[30 32 34 36 38 40]
[10 10 10 10 10 10]
[200 231 264 299 336 375]
[2 1 1 1 1 1]
[100 105 110 115 120 125]
[400 441 484 529 576 625]


### 배열의 인덱싱과 슬라이싱
- 1차원인 경우 - 넘파이배열이름[위치인덱스값]
- 2차원인 경우 - 넘파이배열이름[행,열] = 넘파이배열이름[행][열]

In [191]:
listB = [[100, 200, 300, 400],[1, 2, 3, 4],[5, 6, 7, 8],[500, 600, 700, 800]]
npB = np.array(listB)

print(npB, '\n')
print(npB[2::, ::],'3,4 행 출력\n') # 3,4 행 출력
print(npB[::2][::],'1, 3행 출력\n') # 1, 3행 출력
print(npB[1::2, ::],'2, 4행 출력\n') # 2, 4행 출력

[[100 200 300 400]
 [  1   2   3   4]
 [  5   6   7   8]
 [500 600 700 800]] 

[[  5   6   7   8]
 [500 600 700 800]] 3,4 행 출력

[[100 200 300 400]
 [  5   6   7   8]] 1, 3행 출력

[[  1   2   3   4]
 [500 600 700 800]] 2, 4행 출력



In [199]:
# 1차원 배열의 인덱싱과 슬라이싱
arr1 = np.array([10,20,30,40,50])
print(arr1[-1])
print(arr1[1])
print(arr1[1:3])
print(arr1[1::2])

50
20
[20 30]
[20 40]


In [211]:
# 2차원 배열의 인덱싱과 슬라이싱
# 넘파이배열명[행인덱스, 열인덱스] | 넘파이배열명[행인덱스][열인덱스] 
arr2 = np.array([[100,200,300,400],
                [1,2,3,4],
                [5,6,7,8],
                [500,600,700,800]])
print(arr2)
print(arr2[1,3], arr2[1][3])
print(arr2[0:2, ::])
print(arr2[::, :2:])
print(arr2[::, 2::])
print(arr2[1:3:, 1:3:])

[[100 200 300 400]
 [  1   2   3   4]
 [  5   6   7   8]
 [500 600 700 800]]
4 4
[[100 200 300 400]
 [  1   2   3   4]]
[[100 200]
 [  1   2]
 [  5   6]
 [500 600]]
[[300 400]
 [  3   4]
 [  7   8]
 [700 800]]
[[2 3]
 [6 7]]


In [26]:
# 슬라이드 33 퀴즈
'''
1) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 1,3,5 열만 출력하여라
2) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 1행1열, 1행4열, 3행1열, 3행 4
열만 출력하여라
3) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 홀수번째 행만 출력하여라
'''
matrix_3_5 = np.arange(1,16)[::].reshape(3, 5)
print(matrix_3_5)
print()

# 1)
print(matrix_3_5[::,::2], '\n')

# 2)
print(matrix_3_5[::2,::3], '\n')

# 3)
print(matrix_3_5[::2,::])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]] 

[[ 1  4]
 [11 14]] 

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


### 배열의 데이타 교체
- 넘파이배열명[index] = 값
- 넘파이배열명[rowIndex][columnIndex] = 값

In [213]:
arr = np.arange(1,11)
print(arr)

arr[0] = 10
print(arr)

arr[-1] = 100
print(arr)

arr[7:] = 0
print(arr)

arr[1:3] = -100
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[10  2  3  4  5  6  7  8  9 10]
[ 10   2   3   4   5   6   7   8   9 100]
[10  2  3  4  5  6  7  0  0  0]
[  10 -100 -100    4    5    6    7    0    0    0]


In [214]:
arr2d = np.zeros([3, 5], dtype=int)
print(arr2d, '\n')

arr2d[0, 0] = 10
print(arr2d, '\n')

arr2d[-1, -1] = 20
print(arr2d, '\n')

arr2d[1, ::] = 30
print(arr2d, '\n')

arr2d[::, 1] = 40
print(arr2d, '\n')

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

[[10  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]] 

[[10  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0 20]] 

[[10  0  0  0  0]
 [30 30 30 30 30]
 [ 0  0  0  0 20]] 

[[10 40  0  0  0]
 [30 40 30 30 30]
 [ 0 40  0  0 20]] 



In [218]:
# zeros 초기값은 실수형 => 정수형으로 변환하고 싶으면 dtype=int
arr2d = np.zeros([3, 7])
print(arr2d, '\n')
# print(arr2d.dtype)

arr2d[::, ::2] = 0.5
print(arr2d, '\n')

arr2d[1::, 1:4:] = 3.14
print(arr2d, '\n')

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 

[[0.5 0.  0.5 0.  0.5 0.  0.5]
 [0.5 0.  0.5 0.  0.5 0.  0.5]
 [0.5 0.  0.5 0.  0.5 0.  0.5]] 

[[0.5  0.   0.5  0.   0.5  0.   0.5 ]
 [0.5  3.14 3.14 3.14 0.5  0.   0.5 ]
 [0.5  3.14 3.14 3.14 0.5  0.   0.5 ]] 



In [227]:
arr1 = np.zeros([4,5])
print(arr1)

arr1[1,2] = -5.5
print(arr1)

arr1[0, ::] = 3.3
print(arr1)

arr1[::, -1] = 2.2
print(arr1)

arr1[2:4:, 2:4:] = 1.1
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 0.   0.   0.   0.   0. ]
 [ 0.   0.  -5.5  0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 3.3  3.3  3.3  3.3  3.3]
 [ 0.   0.  -5.5  0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 3.3  3.3  3.3  3.3  2.2]
 [ 0.   0.  -5.5  0.   2.2]
 [ 0.   0.   0.   0.   2.2]
 [ 0.   0.   0.   0.   2.2]]
[[ 3.3  3.3  3.3  3.3  2.2]
 [ 0.   0.  -5.5  0.   2.2]
 [ 0.   0.   1.1  1.1  2.2]
 [ 0.   0.   1.1  1.1  2.2]]
