### 배열의 데이터 추가
- np.insert(배열명, 인덱스, 값) : 1차원 배열의 특정 위치에 값 삽입
- np.insert(배열명, 인덱스, 값, axis=0/1) : 2차원 배열의 특정 위치에 값 삽입
- 축(axis)를 지정하지 않으면 1차원 배열로 반환하며 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [1]:
import numpy as np

In [2]:
# 1차원 배열 추가
# np.insert(배열명, 인덱스 위치, 데이터) => 덮어 씌우지 않고 추가하고 그 뒤는 밀림
arr1 = np.arange(5) # [0,1,2,3,4]
print(arr1, '\n')

# 그냥 출력하면 미리보기이며, 원본에 반영이 되지 않는다.
# 원본에 반영하려면 대입 연산자('=')로 원본에 다시 선언해야 한다.
print(np.insert(arr1, 0, 100), '\n')
print(np.insert(arr1, len(arr1), 200), '\n') # 맨 뒤에 추가
print(np.insert(arr1, -1, 200), '\n')

[0 1 2 3 4] 

[100   0   1   2   3   4] 

[  0   1   2   3   4 200] 

[  0   1   2   3 200   4] 



In [4]:
# 2차원 배열 추가
# np.insert(배열명, 인덱스 위치, 데이터, axis=0|1)
# axis 값이 0이면 행단위, 1이면 열단위

arr2 = np.arange(1,10).reshape(3,3)
print(arr2, '\n')

# 그냥 출력하면 미리보기이며, 원본에 반영이 되지 않는다.
# 원본에 반영하려면 대입 연산자('=')로 원본에 다시 선언해야 한다.
print(np.insert(arr2, 0, [100, 200, 300], axis=0), '\n')
print(np.insert(arr2, 3, [100, 200, 300], axis=0), '\n')

arr2 = np.arange(1,10).reshape(3,3) 
print(arr2, '\n') 

# 그냥 출력하면 미리보기이며, 원본에 반영이 되지 않는다.
# 원본에 반영하려면 대입 연산자('=')로 원본에 다시 선언해야 한다.
print(np.insert(arr2, 0, [100, 200, 300], axis=1), '\n') 
print(np.insert(arr2, 3, [100, 200, 300], axis=1), '\n') 
print(np.insert(arr2, arr2.shape[1] , [100, 200, 300], axis=1), '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[100 200 300]
 [  1   2   3]
 [  4   5   6]
 [  7   8   9]] 

[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [100 200 300]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[100   1   2   3]
 [200   4   5   6]
 [300   7   8   9]] 

[[  1   2   3 100]
 [  4   5   6 200]
 [  7   8   9 300]] 

[[  1   2   3 100]
 [  4   5   6 200]
 [  7   8   9 300]] 



### 배열의 데이터 삭제
- np.delete(배열명, 인덱스) : 1차원 배열에서 인덱스에 해당하는 값 삭제
- np.delete(배열명, 인덱스, axis=0/1) : 2차원 배열에서 인덱스에 해당하는 값 삭제.
- 축(axis)를 지정하지 않으면 1차원 배열로 반환하며 2차원 배열은 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [5]:
# 1차원 배열
arr1 = np.arange(10, 0, -1) 
print(arr1, '\n') 
print(np.delete(arr1, 5), '\n') 
print(np.delete(arr1, -1), '\n')

[10  9  8  7  6  5  4  3  2  1] 

[10  9  8  7  6  4  3  2  1] 

[10  9  8  7  6  5  4  3  2] 



In [11]:
# 2차원 배열
arr2 = np.arange(20,0,-1).reshape(-1,5)
print(arr2, '\n')
print(np.delete(arr2, 0, axis=0), '\n')
print(np.delete(arr2, -1, axis=0), '\n') # 삭제에서 '-1'은 맨 뒤가 삭제

arr2 = np.arange(15,0,-1).reshape(5,3)
print(arr2,'\n')
print(np.delete(arr2, 0),'\n') # axis를 안 넣었을 때 <참고>
print(np.delete(arr2, 0, axis=0),'\n')

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]] 

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]] 

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]] 

[[15 14 13]
 [12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]] 

[14 13 12 11 10  9  8  7  6  5  4  3  2  1] 

[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]] 



### 난수 배열 생성
##### 기본은 실수형으로 생성
- np.random.rand(갯수) , np.random.rand(행수,열수) : 균등 분포
- np.random.randn(갯수) , np.random.randn(행수,열수) : 표준 정규 분포
- np.random.uniform(start, end, 갯수) , np.random.uniform(start, end, (행수,열수) ) : 범위 안에서의 실수 난수
- np.random.randint(start,end, 갯수) , np.random.randint(start,end, (행수,열수)) : 범위 안에서의 정수 난수

In [18]:
print(np.random.randn(5), '\n') 
print(np.random.randn(3,3), '\n') 
print(np.random.uniform(-5, 5, 5), '\n') 
print(np.random.uniform(-5, 5, (4,2)), '\n')
print('='*50)

# start 값 생략시 0 부터 end-1까지 => 정수형
print(np.random.randint(2, size=10),'\n')
print(np.random.randint(-10, 11, size=10),'\n')
print(np.random.randint(10, 99, size=(3, 5)),'\n')

[ 2.37518349 -1.14850962  0.75617445  0.14406246  0.83568931] 

[[-0.23996898  0.58677127 -0.9453961 ]
 [ 1.15239714  0.66178004 -0.09801436]
 [ 0.52902612  0.17822699 -0.14040285]] 

[ 0.7520604   1.52080226 -4.3662771  -4.54983548  0.3697119 ] 

[[-3.60822669  3.0245338 ]
 [-1.3399713  -0.59419179]
 [-1.47196712  2.0818559 ]
 [-0.55551123 -1.00991162]] 

[0 1 1 1 0 1 0 1 0 0] 

[ -2   1   6  10   3   2   7 -10  -6   6] 

[[35 41 22 28 19]
 [76 79 24 88 97]
 [47 48 37 60 66]] 



### 배열 데이타 무작위 선택
np.random.choice()
- 리스트에서 무작위로 n개의 데이터를 추출할 때 사용한다.
- np.random.choice(양의정수|데이타리스트, size=샘플숫자, replace=True/False, p=확률리스트)
- 데이타형이 리스트이면 데이터, 정수이면 arange(a) 명령으로 데이터를 생성한다.
- Size : 정수. 샘플 숫자
- replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능하다. 중복허용
- p : 리스트형태로 각 데이터가 선택될 수 있는 확률로 소숫점 단위로 지정. 합은 1이어야한다

In [24]:
print(np.random.choice(11, 5, replace=False))
print(np.random.choice(11, 5, replace=True))

# 선택 확률을 다르게 해서 2개 선택 # 0~4 범위에서 1,2,3 숫자중 선택 
# 확률배율 p=소숫점아래배열로구성
print(np.random.choice(5, 10, p=[0, 0.3, 0.3, 0.4, 0]))
print(np.random.choice(5, 10, p=[0, 0.3, 0.3, 0.4, 0])) 
print(np.random.choice(5, 10, p=[0, 0.3, 0.3, 0.4, 0]))

[ 0 10  3  4  9]
[6 5 4 7 4]
[3 3 1 3 2 2 1 1 1 3]
[2 1 1 3 3 2 2 3 2 1]
[1 3 2 3 2 2 3 1 1 1]


In [29]:
# 데이터 뽑기
# 10번 기회중에서 꽝이 나올 확률은 0.6
gift_list = ['꽝','하와이 왕복티켓 2매', '스타벅스 상품권 5만원' ] 
for i in range(10):
     print(f'{i+1}번', np.random.choice(gift_list, 1, p=[0.6, 0.05, 0.35]))

1번 ['하와이 왕복티켓 2매']
2번 ['꽝']
3번 ['스타벅스 상품권 5만원']
4번 ['스타벅스 상품권 5만원']
5번 ['꽝']
6번 ['스타벅스 상품권 5만원']
7번 ['꽝']
8번 ['꽝']
9번 ['꽝']
10번 ['꽝']


In [233]:
# 로또 번호 생성기 (1~46, 6개, 중복x)
for i in range(5):
    lotto_list = np.random.choice(np.arange(1,46), size=6, replace=False)
    print(lotto_list)

[23  7 24 42 12 29]
[ 6 38  7 45 17 33]
[20 21 34  7 23 44]
[18 27 32 20  8 37]
[29  6 43 28  5 20]


In [269]:
# 데이타 섞기, 원본에 바로 반영
# np.random.shuffle(집합형자료)
'''
- 원본집합형자료(리스트, 넘파이배열)의 순서가 변경된다
- np.random.shuffle(집합형자료)
'''

arr = np.arange(1,10)
print(arr, '\n')

np.random.shuffle(arr)
print(arr, '\n')

np.random.shuffle(arr)
print(arr, '\n')

arr = np.arange(1,26)
print(arr,'\n')
np.random.shuffle(arr)
print(arr)

[1 2 3 4 5 6 7 8 9] 

[7 5 2 8 1 9 6 3 4] 

[5 6 8 4 2 1 9 3 7] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25] 

[13 15  2  8 17  3 19 20  7 21 10  1  6  4 16 12 25  5 23 24 14  9 18 11
 22]


In [244]:
# np.random.seed()
# 시드 설정 => 100
'''
- 한번 발생한 난수를 다시 표시할 때 사용
- np.random.seed(숫자)
'''

# 시드 0으로 설정 후 난수 배열 생성
np.random.seed(100)
print(np.random.randint(1, 10, 3))

[9 9 4]


In [245]:
# 시드 없이 난수 생성
np.random.randint(1, 10, 3)

array([8, 8, 1])

In [267]:
# 시드 다시 설정 => 100
np.random.seed(100)
print(np.random.randint(1,10,3))

[9 9 4]


In [309]:
# - np.maximum(배열1, 배열2), np.minimum(배열1, 배열2)
#      => 두 개의 배열에서 같은 인덱스 위치의 큰 숫자 또는 작은 숫자만 추출

arr1 = np.random.randint(10,100,5)
arr2 = np.random.randint(10,100,5)
arr3 = np.random.randint(10,100,5)

arr4 = np.maximum(arr1, arr2)
arr5 = np.minimum(arr1, arr2)

print(arr1)
print(arr2)
# print(arr3)
print()
# print('maximun :', arr4,'| minimun :', arr5)



[23 32 97 93 85]
[21 41 48 59 26]

maximun : [23 41 97 93 85] | minimun : [21 32 48 59 26]


In [319]:
# np.통계함수(배열명, axis=0|1)
# 통계함수 sum(), mean(), median(), max(), min()...
'''
- 같은 배열에서 최댓값이나 최솟값을 추출
- 2차원 배열에서는 axis 값을 지정하여 같은 행이나 열에서 최댓값이나 최솟값 추출
- np.max(배열), np.min(배열)
- np.max/np.min(배열, axis=0), np.max/np.min(배열, axis=1)
'''

# 1차원 배열
arr1 = np.random.randint(1,10,5)
print(arr1)
print(np.sum(arr1), np.mean(arr1), np.median(arr1), np.max(arr1), np.min(arr1))

print('='*50)

# 2차원 배열
# 5행 4열
arr2 = arr1 = np.random.randint(1, 20, (5,4))
print(arr2,'\n')

print(np.sum(arr2),'\n') # 모든 합
print(np.sum(arr2, axis=0),'\n') # 열 단위 같은 인덱스 위치의 데이터 합  => 반환 결과 값이 행 단위 개수
print(np.sum(arr2, axis=1),'\n') # 각 행의 데이터 합 => 반환 결과 값이 열 단위 개수

[6 4 8 7 6]
31 6.2 6.0 8 4
[[ 8 12 12 16]
 [ 5  8 19  2]
 [11 17  3  1]
 [ 3  6  5  4]
 [18 18  4  3]] 

175 

[45 61 43 26] 

[48 34 32 18 43] 



In [328]:
'''
- np.sort(배열1차) / 배열명.sort() : 오름차순
- np.sort(배열1차)[::-1] : 내림차순
- np.sort(배열2차, axis=0/1)[::-1]|[::,::-1]
'''

# 1차원 배열
npArr = np.random.randint(1, 99, 5)
print(npArr)
print(np.sort(npArr))
print(np.sort(npArr)[::-1])
print('='*50,'\n')

# 2차원 배열
npArr = np.array([[10, -99, 12], [-5, -45, 21], [7, -89, 33]])
print(npArr,'\n')

# 열 단위 정렬(인덱스 위치가 같은 열에서 정렬)
print(np.sort(npArr),'\n') # => axis=1의 결과와 데이터 같음(행 단위 오름차순)
print(np.sort(npArr, axis=0),'\n')
print(np.sort(npArr, axis=0)[::-1],'\n') # 정렬 결과를 역순으로 반환

# 행 단위 정렬
print(np.sort(npArr, axis=1),'\n')
print(np.sort(npArr, axis=1)[::, ::-1],'\n') # 정렬 결과를 역순으로 반환

[35 62 77  3 21]
[ 3 21 35 62 77]
[77 62 35 21  3]

[[ 10 -99  12]
 [ -5 -45  21]
 [  7 -89  33]] 

[[-99  10  12]
 [-45  -5  21]
 [-89   7  33]] 

[[ -5 -99  12]
 [  7 -89  21]
 [ 10 -45  33]] 

[[ 10 -45  33]
 [  7 -89  21]
 [ -5 -99  12]] 

[[-99  10  12]
 [-45  -5  21]
 [-89   7  33]] 

[[ 12  10 -99]
 [ 21  -5 -45]
 [ 33   7 -89]] 



### 중복값 제거
- np.unique(배열명)

In [329]:
names = np.array(['Charles','Julia', 'Hayoung','Charles', 'Hayoung','Julia','Julia'])
print(names)
print(np.unique(names)) # soring까지 됨

['Charles' 'Julia' 'Hayoung' 'Charles' 'Hayoung' 'Julia' 'Julia']
['Charles' 'Hayoung' 'Julia']


In [349]:
arr1 = np.array([6,6,1,4,2,3,3,1,4,6,1,2,4,2,2,3,1,5,2,5,6,6,6,3,3,2,4])
print(arr1)
print(np.unique(arr1))
print('='*50)

arr2 = np.random.randint(1,10,(5,6))
print(arr2)
print(np.unique(arr2))

[6 6 1 4 2 3 3 1 4 6 1 2 4 2 2 3 1 5 2 5 6 6 6 3 3 2 4]
[1 2 3 4 5 6]
[[3 1 7 9 9 2]
 [8 3 4 6 6 6]
 [8 8 8 8 8 9]
 [7 1 2 7 8 3]
 [3 5 2 2 1 6]]
[1 2 3 4 5 6 7 8 9]


### All & Any
- all(조건식) : 모든 값이 조건식에 만족하면 True (and)
- any(조건식) : 값 중 하나만 만족하면 True (or)

In [425]:
arr = np.array([1, -90, 0, 30, -88])
print(arr, '\n')
print(arr>0, '\n')
print(all(arr>0), any(arr>0)) # arr에 0, 음수가 있기 때문에 all은 False, any는 True 반환

'''
print(arr1 > 0)
print(arr2 > 0) 
print(arr3 > 0) 
print(all(arr1 > 0), all(arr2 > 0), all(arr3 > 0))
print(any(arr1 > 0), any(arr2 > 0), any(arr3 > 0))
print(not any(arr1 > 0), not any(arr2 > 0), not any(arr3 > 0))
'''

[  1 -90   0  30 -88] 

[ True False False  True False] 

False True
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[False  True  True  True  True]
[False  True  True  True False]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [364]:
# all(조건식) => and , any(조건식) => or
arr1 = np.array([1, -90, 0, 30, -88])
arr2 = np.array([1, 90, 78, 30, 88])
arr3 = np.array([-1, -90, 0, -30, -88])

print(arr1 > 0)
print(arr2 > 0)
print(arr3 > 0)
print()

print(arr1 > 0)
print(arr2 > 0)
print(arr3 > 0)
print()

print(all(arr1 > 0), all(arr2 > 0), all(arr3 > 0))
print(any(arr1 > 0), any(arr2 > 0), any(arr3 > 0))

[ True False False  True False]
[ True  True  True  True  True]
[False False False False False]

[ True False False  True False]
[ True  True  True  True  True]
[False False False False False]

False True False
True True False


### np.where()
- np.where(조건식, True, False) : 조건식에 만족하면 True 해당하는 값 표시, 그렇지 않으면 False에 해당하는 값 표시

In [374]:
arr = np.random.randint(-10, 11, 5)
print(arr, '\n')
print(np.where(arr>=0, True, False))
print(np.where(arr>0, '양수', '0 또는 음수'))

[-5  0  6 -3  2] 

[False  True  True False  True]
['0 또는 음수' '0 또는 음수' '양수' '0 또는 음수' '양수']


## Boolean Indexing
- 다수개의 배열에서 특정 조건에 맞는 값을 추출할 때 사용
- 배열[조건] : TRUE, FALSE로 값이 표시
- 논리 연산자 : |(or 연산자), &(and 연산자), ~(not 연산자)
- 배열[조건]을 배열의 대괄호 [] 안에 삽입하면 True에 해당하는 데이타만 추출
- 배열[배열[조건]]

In [414]:
# 80보다 크거나 -80보다 작은 데이터로 구성된 넘파이 배열이 추출된다
# 0보다 크거나 -50보다 작은 데이터로 구성된 넘파이 배열이 추출된다

# 1차원 배열
arr = np.random.randint(-99, 100, (7,7))  # -99~99 사이의 난수로 7x7 행렬 생성
print(arr, '\n')

print((arr>80) | (arr<-80), '\n') # True|False 반환

print(arr[(arr>80) | (arr<-80)], '\n')

print(arr[(arr>0) & (arr%2==0)], '\n')

print(arr[~(arr<50) & ~(arr%2==0)], '\n')

[[ 29   2  29 -53 -91 -80  13]
 [-13 -51 -75  92  59 -81  77]
 [  4 -39 -44   7  11  74  28]
 [-68  52  44   7  88 -12 -69]
 [ 36  95  -8  71 -27  53  10]
 [ 87 -36  26 -87  82  87  -5]
 [ 33 -98  45  72 -91  80 -30]] 

[[False False False False  True False False]
 [False False False  True False  True False]
 [False False False False False False False]
 [False False False False  True False False]
 [False  True False False False False False]
 [ True False False  True  True  True False]
 [False  True False False  True False False]] 

[-91  92 -81  88  95  87 -87  82  87 -98 -91] 

[ 2 92  4 74 28 52 44 88 36 10 26 82 72 80] 

[59 77 95 71 53 87 87] 



In [415]:
# 2차원 배열
arr2 = np.random.randint(-100, 101, (4, 5) )
print(arr2, '\n')

# 양수만 출력
print(arr2 > 0, '\n')
print(arr2[arr2 > 0], '\n')

# 1행
print(arr2[0,:], '\n')
print(arr2[0,:] > 0, '\n')

# 1행을 열의 마스크로 적용
# 1행에서 양수인 데이터에 해당하는 열이 출력
# 행과 열의 수가 달라서 조건식이 열에 대한 정렬인 경우 행의 전체를 잡기 위해 [:, 조건식] 형태로 적용
# 따라서, 2차원 형태로 변수명[:, 변수명[:, 조건식]] 형태
print(arr2[:, arr2[0,:] > 0], '\n')

[[-51  27 -11 -36  60]
 [ 19   2   9 -19 -44]
 [-83  38  22  53 -53]
 [ 78 -60 -38 -83  41]] 

[[False  True False False  True]
 [ True  True  True False False]
 [False  True  True  True False]
 [ True False False False  True]] 

[27 60 19  2  9 38 22 53 78 41] 

[-51  27 -11 -36  60] 

[False  True False False  True] 

[[ 27  60]
 [  2 -44]
 [ 38 -53]
 [-60  41]] 



In [416]:
# 1열의 값 중 50보다 큰 행만 추출된다

# 2차원 형태
# 행과 열의 수가 같아서 조건식[:,:]을 어디에 걸어도 그 해당하는 결과 반환 가능
print(arr, '\n')
print(arr[:, 0]>50, '\n')
print(arr[arr[:, 0]>50], '\n')

[[ 29   2  29 -53 -91 -80  13]
 [-13 -51 -75  92  59 -81  77]
 [  4 -39 -44   7  11  74  28]
 [-68  52  44   7  88 -12 -69]
 [ 36  95  -8  71 -27  53  10]
 [ 87 -36  26 -87  82  87  -5]
 [ 33 -98  45  72 -91  80 -30]] 

[False False False False False  True False] 

[[ 87 -36  26 -87  82  87  -5]] 



## Fancy Indexing
- 배열을 index value로 사용해서 값을 얻는 방법
- 넘파이배열1[정수형넘파이배열2]
- 넘파이배열1[정수형넘파이배열2, 정수형넘파이배열3]

In [423]:
# 1차원 배열의 Fancy indexing
arr1 = np.arange(1, 10, dtype=float) + 0.05
arr2 = np.array([0, 0, 1, 5, 7, -1, -2])

print(arr1,'\n')
print(arr2,'\n')
print('='*50)
print(arr1[arr2],'\n')
# print(arr2[arr1],'\n') # IndexError

[1.05 2.05 3.05 4.05 5.05 6.05 7.05 8.05 9.05] 

[ 0  0  1  5  7 -1 -2] 

[1.05 1.05 2.05 6.05 8.05 9.05 8.05] 



In [424]:
# 2차원 배열의 Fancy indexing
arr1 = np.random.randint(10, 51, (5,5))
arr2 = np.array([0, 1, 2, 3, 4])
arr3 = np.array([-1, 3, 2, 1, 0])

print(arr1,'\n')
print(arr2,'\n')
print(arr3,'\n')
print('='*50)
print(arr1[arr2, arr3],'\n') # arr2: 행 인덱스 | arr3: 열 인덱스

[[41 35 40 37 12]
 [47 39 30 29 48]
 [42 15 12 10 41]
 [14 16 23 34 33]
 [27 17 22 26 29]] 

[0 1 2 3 4] 

[-1  3  2  1  0] 

[12 29 12 16 27] 

